services:
  - type: web
    name: cycling-breaks
    env: node
    rootDir: app
    buildCommand: corepack enable && yarn install --immutable && yarn build
    startCommand: yarn start
    plan: starter
    envVars:
      - key: NODE_VERSION
        value: 26.x
