services:
  - type: web
    name: cycling-breaks
    env: node
    rootDir: app
    buildCommand: yarn install --immutable && yarn build
    startCommand: yarn start
    plan: starter
    envVars:
      - key: NODE_VERSION
        value: 26.x
      - key: NODE_OPTIONS
        value: "--max-old-space-size=448"
